### PR TITLE
Use /bin/diff as diff command to avoid custom aliases

### LINKED ISSUE #109: List index out of range error when stripping modified lines
This is the only contents of my `.vimrc`:
```
call plug#begin('~/.vim/plugged')
Plug 'ntpeters/vim-better-whitespace'
call plug#end()

let g:strip_whitespace_on_save=1
let g:strip_only_modified_lines=1
```

When changing a line with trailing whitespace in a file and then saving, I get the following error:
```
Error detected while processing function <SNR>18_StripWhitespaceOnSave:
line    8:
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
E116: Invalid arguments for function <SID>DetectWhitespace(r[0], r[1])
E684: list index out of range: 1
```

### PR DESCRIPTION
**Pull request by Tyilo**
This fixes #109

### CODE REVIEW

**Comment by Cimbali** [comment]
Hmm. On my system (and I suppose a number of other systems as well), diff is `/usr/bin/diff` so this won’t work.

Maybe rather than bypassing aliases, we could offer an option for people to use their own diff command/binary ? That way we support both people with aliases and people that want to diff binaries that are not installed in standard locations, as well as passing custom options to diff, etc.

Probably this could be bundled with a better error message (something along the lines of “check your diff command”) to guide people the right way if they have an alias.

**Comment by Tyilo** [comment]
Hmm, I guess `/usr/bin/diff` is better.

**Comment by Tyilo** [comment]
Another option would be to use `command diff` instead of `diff` to bypass builtin functions.

**Comment by Cimbali** [comment]
`command diff` would work on all *nix systems to bypass aliases, but not on windows I believe.

**Comment by ntpeters** [comment]
Resolved in #121

**Pull request closed without merging**
